from __future__ import annotations

import math
import threading
from datetime import date, datetime
from decimal import Decimal
from typing import Any, Literal
from uuid import UUID

import numpy as np
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import func, inspect, select
from sqlalchemy.orm import Session

from app.clinical_ranges import LAB_RANGES, VITAL_RANGES
from app.db.session import get_db
from app.models import Condition, Encounter, LabResult, Patient, RiskPrediction, Vital
from app.similarity import MODEL_VERSION, get_risk_cache

router = APIRouter()
_SNAPSHOT_LOCK = threading.Lock()
_SNAPSHOT: dict[str, Any] | None = None

TABLE_MODELS = {
    "patients": Patient,
    "encounters": Encounter,
    "conditions": Condition,
    "lab_results": LabResult,
    "vitals": Vital,
    "risk_predictions": RiskPrediction,
}

TABLE_INFO = {
    "patients": {
        "description": "Synthetic patient demographics and Synthea identifiers.",
        "source": "Synthea patients.csv: Id, BIRTHDATE, GENDER, RACE, ETHNICITY; smoking status from observations.csv code 72166-2.",
    },
    "encounters": {
        "description": "Patient visits and encounter context.",
        "source": "Synthea encounters.csv: PATIENT, ENCOUNTERCLASS, START, STOP, REASONDESCRIPTION (REASONCODE fallback).",
    },
    "conditions": {
        "description": "Patient diagnoses with active or resolved status.",
        "source": "Synthea conditions.csv: PATIENT, CODE, DESCRIPTION, START, STOP; STOP determines resolved status.",
    },
    "lab_results": {
        "description": "Numeric non-vital observations, including known lab reference ranges.",
        "source": "Synthea observations.csv numeric rows not mapped to vital codes; CODE, DISPLAY/DESCRIPTION, VALUE, UNITS, DATE; ranges from clinical_ranges.py when known.",
    },
    "vitals": {
        "description": "Wide-format daily vital measurements for each patient.",
        "source": "Synthea observations.csv vital LOINC codes 8867-4, 8480-6, 8462-4, 9279-1, 8310-5, 59408-5, and 2708-6; grouped by patient and UTC day.",
    },
    "risk_predictions": {
        "description": "Audit log of explicitly persisted risk computations.",
        "source": "Generated by the API when a risk request is persisted; not imported from Synthea.",
    },
}

COLUMN_INFO = {
    "patients": {
        "id": "Internal UUID.",
        "mrn": "Synthea patient Id, retained as a stable external key.",
        "date_of_birth": "Synthea BIRTHDATE.",
        "sex": "Synthea GENDER mapped to male or female; other values become unknown.",
        "ethnicity": "Synthea RACE, or hispanic when ETHNICITY is hispanic.",
        "smoking_status": 'Synthea observation "Tobacco smoking status" (LOINC 72166-2), mapped to never, former, or current when available.',
        "created_at": "Database insertion timestamp.",
    },
    "encounters": {
        "id": "Internal UUID.",
        "patient_id": "Internal UUID referencing patients.id.",
        "encounter_type": "Synthea ENCOUNTERCLASS.",
        "started_at": "Synthea START.",
        "ended_at": "Synthea STOP, when present.",
        "reason": "Synthea REASONDESCRIPTION, falling back to REASONCODE.",
    },
    "conditions": {
        "id": "Internal UUID.",
        "patient_id": "Internal UUID referencing patients.id.",
        "code": "Synthea condition CODE as provided in the source CSV.",
        "display": "Synthea DESCRIPTION.",
        "recorded_at": "Synthea START.",
        "status": "Active unless Synthea STOP is present, in which case resolved.",
    },
    "lab_results": {
        "id": "Internal UUID.",
        "patient_id": "Internal UUID referencing patients.id.",
        "test_code": "Synthea observation CODE (LOINC where supplied).",
        "test_name": "Synthea DISPLAY, falling back to DESCRIPTION.",
        "value": "Numeric Synthea observation VALUE.",
        "unit": "Synthea UNITS, or n/a when missing.",
        "measured_at": "Synthea observation DATE.",
        "reference_low": "Known lower reference bound from clinical_ranges.py; otherwise null.",
        "reference_high": "Known upper reference bound from clinical_ranges.py; otherwise null.",
    },
    "vitals": {
        "id": "Internal UUID.",
        "patient_id": "Internal UUID referencing patients.id.",
        "measured_at": "Latest source observation time for that patient and UTC day.",
        "heart_rate": "Observation code 8867-4, heart rate.",
        "systolic_bp": "Observation code 8480-6, systolic blood pressure.",
        "diastolic_bp": "Observation code 8462-4, diastolic blood pressure.",
        "respiratory_rate": "Observation code 9279-1, respiratory rate.",
        "temperature_c": "Observation code 8310-5, converted/retained as the source numeric value.",
        "oxygen_saturation": "Observation code 59408-5 or 2708-6.",
    },
    "risk_predictions": {
        "id": "Internal UUID.",
        "patient_id": "Internal UUID referencing patients.id.",
        "risk_score": "Computed score in the range 0-1.",
        "risk_category": "low, moderate, or high category for the score.",
        "model_version": "Version identifier for the scoring implementation.",
        "top_similar_patients": "JSON audit details for the selected neighboring patients and similarities.",
        "explanation": "JSON audit details for risk components, weights, and out-of-range measures.",
        "predicted_at": "Database timestamp when the result was persisted.",
    },
}


def invalidate_snapshot() -> None:
    global _SNAPSHOT
    with _SNAPSHOT_LOCK:
        _SNAPSHOT = None


def _as_json(value: Any) -> Any:
    if isinstance(value, (UUID, date, datetime)):
        return value.isoformat() if not isinstance(value, UUID) else str(value)
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, dict):
        return {str(key): _as_json(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_as_json(item) for item in value]
    if isinstance(value, np.generic):
        return value.item()
    return value


def _age(patient: Patient, encounter_dates: dict[UUID, datetime]) -> int:
    latest = encounter_dates.get(patient.id)
    if latest is None:
        return 65
    return max(0, int(((latest.date() - patient.date_of_birth).days) / 365.25))


def _category_counts(items: list[dict[str, Any]]) -> dict[str, int]:
    return {
        category: sum(item["risk_category"] == category for item in items)
        for category in ("low", "moderate", "high")
    }


def _get_snapshot(db: Session, refresh: bool = False) -> dict[str, Any]:
    global _SNAPSHOT
    with _SNAPSHOT_LOCK:
        if refresh:
            _SNAPSHOT = None
        if _SNAPSHOT is not None:
            return _SNAPSHOT

        cache = get_risk_cache(db, refresh=refresh)
        patients = cache["patients"]
        patient_map = {patient.id: patient for patient in patients}
        conditions = list(db.scalars(select(Condition).order_by(Condition.recorded_at.desc())))
        condition_counts: dict[UUID, int] = {}
        active_conditions: dict[str, set[UUID]] = {}
        for condition in conditions:
            condition_counts[condition.patient_id] = condition_counts.get(condition.patient_id, 0) + 1
            if condition.status != "resolved":
                active_conditions.setdefault(condition.display, set()).add(condition.patient_id)

        rows = []
        for patient_id in cache["patient_ids"]:
            patient = patient_map[patient_id]
            risk = cache["default_scores"][patient_id]
            rows.append({
                "id": patient_id,
                "mrn": patient.mrn or "",
                "age": _age(patient, cache["encounter_dates"]),
                "sex": patient.sex,
                "ethnicity": patient.ethnicity or "unknown",
                "smoking_status": patient.smoking_status or "unknown",
                "risk_score": risk["risk_score"],
                "risk_category": risk["risk_category"],
                "own_risk": cache["own_risk"].get(patient_id, 0.0),
                "neighbor_fraction": risk["neighbor_fraction"],
                "out_of_range": cache["out_of_range"].get(patient_id, []),
                "condition_count": condition_counts.get(patient_id, 0),
            })

        counts = {
            "patient_count": len(patients),
            "encounter_count": db.scalar(select(func.count()).select_from(Encounter)) or 0,
            "condition_count": len(conditions),
            "lab_count": db.scalar(select(func.count()).select_from(LabResult)) or 0,
            "vital_count": db.scalar(select(func.count()).select_from(Vital)) or 0,
            "prediction_log_count": db.scalar(select(func.count()).select_from(RiskPrediction)) or 0,
        }
        patient_ids_with_vitals = set(db.scalars(select(Vital.patient_id).distinct()))
        lab_rows_with_ranges = db.scalar(
            select(func.count()).select_from(LabResult).where(
                (LabResult.reference_low.is_not(None)) | (LabResult.reference_high.is_not(None))
            )
        ) or 0
        first_encounter, last_encounter = db.execute(
            select(func.min(Encounter.started_at), func.max(Encounter.started_at))
        ).one()
        _SNAPSHOT = {
            "cache": cache,
            "patients": patient_map,
            "rows": rows,
            "conditions": conditions,
            "active_conditions": active_conditions,
            "counts": counts,
            "data_quality": {
                "patients_without_vitals": max(0, counts["patient_count"] - len(patient_ids_with_vitals)),
                "pct_labs_with_reference_range": lab_rows_with_ranges / max(counts["lab_count"], 1) * 100,
            },
            "data_span": {
                "first_encounter": _as_json(first_encounter),
                "last_encounter": _as_json(last_encounter),
            },
        }
        return _SNAPSHOT


def _overview(snapshot: dict[str, Any]) -> dict[str, Any]:
    rows = snapshot["rows"]
    counts = _category_counts(rows)
    return {
        **snapshot["counts"],
        "category_counts": counts,
        "avg_risk": sum(row["risk_score"] for row in rows) / max(len(rows), 1),
        "model_version": MODEL_VERSION,
        "weights": {"own_risk": 0.6, "neighbor_fraction": 0.4},
        "thresholds": {"moderate": 0.33, "high": 0.66, "high_risk_label": 0.5},
        "data_span": snapshot["data_span"],
        "data_quality": snapshot["data_quality"],
    }


def _group_summary(rows: list[dict[str, Any]], key: str) -> dict[str, dict[str, Any]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        label = str(row.get(key) or "unknown")
        groups.setdefault(label, []).append(row)
    return {
        label: {
            "n": len(group),
            "avg_risk": sum(item["risk_score"] for item in group) / len(group),
            "category_counts": _category_counts(group),
        }
        for label, group in sorted(groups.items(), key=lambda item: item[0].lower())
    }


def _results(snapshot: dict[str, Any], db: Session) -> dict[str, Any]:
    rows = snapshot["rows"]
    cache = snapshot["cache"]
    bins = [{"range": f"{index / 10:.1f}-{(index + 1) / 10:.1f}", "start": index / 10, "end": (index + 1) / 10, "count": 0} for index in range(10)]
    for row in rows:
        index = min(9, int(row["risk_score"] * 10))
        bins[index]["count"] += 1

    age_buckets = [("0-17", 0, 17), ("18-34", 18, 34), ("35-49", 35, 49), ("50-64", 50, 64), ("65-79", 65, 79), ("80+", 80, None)]
    by_age = {}
    for label, lower, upper in age_buckets:
        group = [row for row in rows if row["age"] >= lower and (upper is None or row["age"] <= upper)]
        by_age[label] = {
            "n": len(group),
            "avg_risk": sum(row["risk_score"] for row in group) / max(len(group), 1),
            "category_counts": _category_counts(group),
        }

    active_conditions = snapshot["active_conditions"]
    top_conditions = []
    risks = {row["id"]: row["risk_score"] for row in rows}
    for display, patient_ids in sorted(active_conditions.items(), key=lambda item: (-len(item[1]), item[0].lower()))[:10]:
        top_conditions.append({
            "display": display,
            "patients": len(patient_ids),
            "avg_risk": sum(risks.get(patient_id, 0.0) for patient_id in patient_ids) / len(patient_ids),
        })

    measure_specs = [(name, name, limits) for name, limits in VITAL_RANGES.items()]
    measure_specs.extend((meta["name"], code, meta) for code, meta in LAB_RANGES.items())
    frequency = []
    observations = cache["latest_observations"]
    for measure, source_key, limits in measure_specs:
        available = 0
        out_count = 0
        for values in observations.values():
            value = values.get(source_key)
            if value is None:
                continue
            available += 1
            if (limits.get("low") is not None and value < limits["low"]) or (limits.get("high") is not None and value > limits["high"]):
                out_count += 1
        frequency.append({
            "measure": measure,
            "patients_with_data": available,
            "patients_out_of_range": out_count,
            "pct": out_count / max(available, 1) * 100,
        })
    frequency.sort(key=lambda item: (-item["pct"], item["measure"]))

    sample_size = min(300, len(rows))
    stride = max(1, math.ceil(len(rows) / max(sample_size, 1)))
    components = [
        {
            "own_risk": row["own_risk"],
            "neighbor_fraction": row["neighbor_fraction"],
            "category": row["risk_category"],
        }
        for row in rows[::stride][:300]
    ]
    top_risk = sorted(rows, key=lambda row: (-row["risk_score"], str(row["id"])))[:10]
    top_risk_patients = [{
        "patient_id": str(row["id"]),
        "mrn": row["mrn"],
        "age": row["age"],
        "sex": row["sex"],
        "risk_score": row["risk_score"],
        "risk_category": row["risk_category"],
        "top_out_of_range": [item["measure"] for item in row["out_of_range"][:3]],
    } for row in top_risk]

    prediction_rows = db.execute(
        select(RiskPrediction, Patient.mrn)
        .join(Patient, Patient.id == RiskPrediction.patient_id)
        .order_by(RiskPrediction.predicted_at.desc())
        .limit(10)
    ).all()
    recent_predictions = [{
        "patient_id": str(prediction.patient_id),
        "mrn": mrn or "",
        "risk_score": float(prediction.risk_score),
        "risk_category": prediction.risk_category,
        "model_version": prediction.model_version,
        "predicted_at": _as_json(prediction.predicted_at),
    } for prediction, mrn in prediction_rows]

    return {
        "patients_with_out_of_range": sum(bool(row["out_of_range"]) for row in rows),
        "score_histogram": bins,
        "by_age": by_age,
        "by_sex": _group_summary(rows, "sex"),
        "by_smoking": {
            status: _group_summary(rows, "smoking_status").get(status, {
                "n": 0,
                "avg_risk": 0.0,
                "category_counts": {"low": 0, "moderate": 0, "high": 0},
            })
            for status in ("never", "former", "current", "unknown")
        },
        "by_ethnicity": _group_summary(rows, "ethnicity"),
        "top_conditions": top_conditions,
        "out_of_range_frequency": frequency,
        "score_components_sample": components,
        "top_risk_patients": top_risk_patients,
        "recent_predictions": recent_predictions,
    }


@router.get("/stats/overview")
def stats_overview(db: Session = Depends(get_db), refresh: bool = False) -> dict[str, Any]:
    return _overview(_get_snapshot(db, refresh=refresh))


@router.get("/stats/results")
def stats_results(db: Session = Depends(get_db), refresh: bool = False) -> dict[str, Any]:
    snapshot = _get_snapshot(db, refresh=refresh)
    return _results(snapshot, db)


@router.get("/patients/search")
def search_patients(
    q: str = "",
    sex: str | None = None,
    category: Literal["low", "moderate", "high"] | None = None,
    sort: Literal["risk_score", "age", "mrn"] = "mrn",
    order: Literal["asc", "desc"] = "asc",
    limit: int = Query(25, ge=1, le=100),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    snapshot = _get_snapshot(db)
    normalized_query = q.casefold()
    filtered = [row for row in snapshot["rows"] if (
        not normalized_query
        or row["mrn"].casefold().startswith(normalized_query)
        or str(row["id"]).casefold().startswith(normalized_query)
    )]
    if sex:
        filtered = [row for row in filtered if row["sex"].casefold() == sex.casefold()]
    if category:
        filtered = [row for row in filtered if row["risk_category"] == category]
    filtered.sort(key=lambda row: (row[sort] is None, row[sort] if sort != "mrn" else row[sort].casefold()), reverse=order == "desc")
    total = len(filtered)
    return {
        "total": total,
        "items": [{key: row[key] for key in (
            "id", "mrn", "age", "sex", "ethnicity", "smoking_status", "risk_score", "risk_category", "condition_count"
        )} for row in filtered[offset:offset + limit]],
    }


@router.get("/patients/{patient_id}/history")
def patient_history(patient_id: UUID, db: Session = Depends(get_db)) -> dict[str, Any]:
    if db.get(Patient, patient_id) is None:
        raise HTTPException(status_code=404, detail="Patient not found")

    vitals = list(db.scalars(
        select(Vital).where(Vital.patient_id == patient_id).order_by(Vital.measured_at.desc()).limit(40)
    ))
    vitals.reverse()
    lab_rows = list(db.scalars(
        select(LabResult)
        .where(LabResult.patient_id == patient_id, LabResult.test_code.in_(list(LAB_RANGES)))
        .order_by(LabResult.measured_at.desc())
    ))
    labs: dict[str, list[dict[str, Any]]] = {}
    for lab in lab_rows:
        name = LAB_RANGES[lab.test_code]["name"]
        values = labs.setdefault(name, [])
        if len(values) < 20:
            values.append({
                "measured_at": _as_json(lab.measured_at),
                "value": float(lab.value),
                "unit": lab.unit,
                "reference_low": float(lab.reference_low) if lab.reference_low is not None else LAB_RANGES[lab.test_code]["low"],
                "reference_high": float(lab.reference_high) if lab.reference_high is not None else LAB_RANGES[lab.test_code]["high"],
            })
    encounters = list(db.scalars(
        select(Encounter).where(Encounter.patient_id == patient_id).order_by(Encounter.started_at.desc()).limit(15)
    ))
    conditions = list(db.scalars(
        select(Condition).where(Condition.patient_id == patient_id).order_by(Condition.recorded_at.desc()).limit(50)
    ))
    return {
        "vitals": [_as_json({key: getattr(item, key) for key in (
            "measured_at", "heart_rate", "systolic_bp", "diastolic_bp", "respiratory_rate", "temperature_c", "oxygen_saturation"
        )}) for item in vitals],
        "labs": labs,
        "encounters": [_as_json({key: getattr(item, key) for key in (
            "encounter_type", "started_at", "ended_at", "reason"
        )}) for item in encounters],
        "conditions": [_as_json({key: getattr(item, key) for key in (
            "display", "recorded_at", "status"
        )}) for item in conditions],
    }


@router.get("/meta/tables")
def table_metadata(db: Session = Depends(get_db)) -> dict[str, Any]:
    inspector = inspect(db.get_bind())
    tables = []
    relationships = []
    for table_name, model in TABLE_MODELS.items():
        columns = []
        primary_keys = set(inspector.get_pk_constraint(table_name).get("constrained_columns") or [])
        foreign_keys = inspector.get_foreign_keys(table_name)
        fk_columns = {}
        for foreign_key in foreign_keys:
            referred_table = foreign_key.get("referred_table")
            referred_columns = foreign_key.get("referred_columns") or []
            for local_column, referred_column in zip(foreign_key.get("constrained_columns") or [], referred_columns):
                fk_columns[local_column] = f"{referred_table}.{referred_column}"
            if referred_table:
                relationships.append({
                    "from": table_name,
                    "to": referred_table,
                    "type": "many-to-one",
                    "on_delete": str(foreign_key.get("options", {}).get("ondelete", "NO ACTION")).upper(),
                })
        for column in inspector.get_columns(table_name):
            name = column["name"]
            columns.append({
                "name": name,
                "type": str(column["type"]),
                "nullable": bool(column["nullable"]),
                "primary_key": name in primary_keys,
                "foreign_key": fk_columns.get(name),
                "description": COLUMN_INFO.get(table_name, {}).get(name, "No additional lineage recorded."),
            })
        tables.append({
            "name": table_name,
            "description": TABLE_INFO[table_name]["description"],
            "row_count": db.scalar(select(func.count()).select_from(model)) or 0,
            "columns": columns,
            "indexes": inspector.get_indexes(table_name),
            "source": TABLE_INFO[table_name]["source"],
        })
    return {"tables": tables, "relationships": relationships}


@router.get("/meta/tables/{name}/sample")
def table_sample(
    name: str,
    limit: int = Query(5, ge=1, le=10),
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    model = TABLE_MODELS.get(name)
    if model is None:
        raise HTTPException(status_code=404, detail="Table not found")
    primary_key = list(model.__table__.primary_key.columns)
    statement = select(model).order_by(*primary_key).limit(limit)
    rows = db.scalars(statement)
    return {"name": name, "items": [
        _as_json({column.key: getattr(row, column.key) for column in model.__table__.columns})
        for row in rows
    ]}


@router.get("/meta/ranges")
def clinical_ranges() -> dict[str, Any]:
    return {
        "vitals": VITAL_RANGES,
        "labs": [{"code": code, **values} for code, values in LAB_RANGES.items()],
    }